// About/components/Header.tsx
"use client";
import { useTheme } from "next-themes";

export default function Header() {
  const { theme, setTheme } = useTheme();

  return (
    <header className="flex items-center justify-between py-6 px-8 bg-white dark:bg-neutral-900 shadow-md">
      <span className="text-2xl font-bold text-blue-600">Мусоев Мухаммаджон</span>
      <nav className="space-x-6">
        <a href="#about" className="hover:text-blue-600">Обо мне</a>
        <a href="#skills" className="hover:text-blue-600">Навыки</a>
        <a href="#projects" className="hover:text-blue-600">Проекты</a>
        <a href="#contact" className="hover:text-blue-600">Контакты</a>
        <button
          className="ml-4 px-3 py-1 rounded bg-gray-200 dark:bg-neutral-700"
          onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
        >
          {theme === "dark" ? "🌞" : "🌙"}
        </button>
      </nav>
    </header>
  );
}

// portfolio/portfolio/src/components/Header.vue
<template>
  <header class="bg-gray-800 text-white">
    <div class="container mx-auto flex justify-between items-center p-4">
      <h1 class="text-2xl font-bold">My Portfolio</h1>
      <nav>
        <ul class="flex space-x-4">
          <li><a href="#hero" class="hover:text-gray-400">Home</a></li>
          <li><a href="#about" class="hover:text-gray-400">About</a></li>
          <li><a href="#skills" class="hover:text-gray-400">Skills</a></li>
          <li><a href="#portfolio" class="hover:text-gray-400">Portfolio</a></li>
          <li><a href="#contact" class="hover:text-gray-400">Contact</a></li>
        </ul>
      </nav>
    </div>
  </header>
</template>

<script>
export default {
  name: 'Header'
}
</script>

<style scoped>
</style>
